name: PantheonDemo
description: $description
version: '${version}'

main: com.eclectusstudio.pantheonDemo.PantheonDemo
bootstrapper: com.eclectusstudio.pantheonDemo.PantheonDemoBootstrap
api-version: '26.2'
load: POSTWORLD

authors: [ Eclectus Studio ]

dependencies:
  bootstrap:
    pantheon:
      load: BEFORE
      required: true
      join-classpath: true
  server:
    pantheon:
      load: BEFORE
      required: true
      join-classpath: true
